### ISSUE TITLE
Ruby1.9/2.0でアクセス履歴視覚化が強制終了する

### ISSUE THREAD

**Issue by shokai** [masui/Gyazz#33]
ページリストにアクセスした時に、アクセス履歴視覚化の画像生成がRuby1.9/2.0で動かず
エラーが出ます。

最近のlinuxのRubyはデフォルトで1.9系になっているので、対応した方がいいです
他にもバイナリを扱っている部分はRuby1.9以上だと動かない部分があるかもしれません。

```
Encoding::CompatibilityError - incompatible character encodings: UTF-8 and ASCII-8BIT:
        /Users/sho/src/sinatra/gyazz/lib/png.rb:19:in `png'
        /Users/sho/src/sinatra/gyazz/lib/history.rb:87:in `history_png'
        /Users/sho/src/sinatra/gyazz/gyazz.rb:268:in `block in <top (required)>'
        /Users/sho/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/sinatra-1.4.2/lib/sinatra/base.rb:1415:in `call'
        /Users/sho/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/sinatra-1.4.2/lib/sinatra/base.rb:1415:in `block in compile!'
        /Users/sho/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/sinatra-1.4.2/lib/sinatra/base.rb:944:in `[]'
        /Users/sho/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/sinatra-1.4.2/lib/sinatra/base.rb:944:in `block (3 levels) in route!'
        /Users/sho/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/sinatra-1.4.2/lib/sinatra/base.rb:960:in `route_eval'
```

**Comment by shokai** [comment]
完了したので閉じます
